services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-finance-sdp
    restart: unless-stopped
    ports:
      - "8006:80"
      - "8443:443"
    environment:
      - APP_NAME="Odoo Finance SDP"
      - APP_ENV=local
      - APP_KEY=base64:vtYRZg/ynlWETTu1NiEhNPf2h24J8BBrKRdwkqYXD6c= # Use your real APP_KEY
      - APP_DEBUG=true
      - APP_URL=http://localhost:8006
      - SERVER_NAME=:80
      - DB_CONNECTION=sqlite
    volumes:
      - odoo_finance_storage:/app/storage
    networks:
      - odoo_finance_net

networks:
  odoo_finance_net:
    driver: bridge

volumes:
  odoo_finance_storage:
